name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  tests:
    runs-on: macOS-14
    strategy:
      matrix:
        xcode:
          - '15.2'
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Skip Macro Validation
        run: sudo defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
      - name: Run tests
        run: make test
